[tool.poetry]
name = "demo-agente"
version = "0.1.0"
description = "Demo de un agente AI multi-acción con GPT y Docker"
authors = ["Sebastian Peitiado"]

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.51.0"
ipykernel = "^6.30.1"
langchain = "^0.3.27"
langgraph = "^0.6.8"
python-dotenv = "^1.1.1"
langchain-openai = "^0.3.34"
pydantic = "^2.11.10"
notebook = "^7.4.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
